<a href="https://colab.research.google.com/github/nastyha002/nastyha002/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1_ipynb%22_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл

**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/Global YouTube Statistics.csv', encoding='windows-1252')
df



rank                    Youtuber  subscribers   video views  \
0       1                    T-Series    245000000  2.280000e+11   
1       2              YouTube Movies    170000000  0.000000e+00   
2       3                     MrBeast    166000000  2.836884e+10   
3       4  Cocomelon - Nursery Rhymes    162000000  1.640000e+11   
4       5                   SET India    159000000  1.480000e+11   
..    ...                         ...          ...           ...   
990   991               Natan por Aï¿     12300000  9.029610e+09   
991   992    Free Fire India Official     12300000  1.674410e+09   
992   993                       Panda     12300000  2.214684e+09   
993   994                 RobTopGames     12300000  3.741235e+08   
994   995                Make Joke Of     12300000  2.129774e+09   

             category                       Title  uploads         Country  \
0               Music                    T-Series    20082           India   
1    Film & Animation               youtubemovies        1   United States   
2       Entertainment                     MrBeast      741   United States   
3           Education  Cocomelon - Nursery Rhymes      966   United States   
4               Shows                   SET India   116536           India   
..                ...                         ...      ...             ...   
990            Sports               Natan por Aï¿     1200          Brazil   
991    People & Blogs    Free Fire India Official     1500           India   
992               NaN                 HybridPanda     2452  United Kingdom   
993            Gaming                 RobTopGames       39          Sweden   
994            Comedy                Make Joke Of       62           India   

    Abbreviation   channel_type  ...  subscribers_for_last_30_days  \
0             IN          Music  ...                     2000000.0   
1             US          Games  ...                           NaN   
2             US  Entertainment  ...                     8000000.0   
3             US      Education  ...                     1000000.0   
4             IN  Entertainment  ...                     1000000.0   
..           ...            ...  ...                           ...   
990           BR  Entertainment  ...                      700000.0   
991           IN          Games  ...                      300000.0   
992           GB          Games  ...                        1000.0   
993           SE          Games  ...                      100000.0   
994           IN         Comedy  ...                      100000.0   

     created_year  created_month  created_date  \
0          2006.0            Mar          13.0   
1          2006.0            Mar           5.0   
2          2012.0            Feb          20.0   
3          2006.0            Sep           1.0   
4          2006.0            Sep          20.0   
..            ...            ...           ...   
990        2017.0            Feb          12.0   
991        2018.0            Sep          14.0   
992        2006.0            Sep          11.0   
993        2012.0            May           9.0   
994        2017.0            Aug           1.0   

     Gross tertiary education enrollment (%)    Population  Unemployment rate  \
0                                       28.1  1.366418e+09               5.36   
1                                       88.2  3.282395e+08              14.70   
2                                       88.2  3.282395e+08              14.70   
3                                       88.2  3.282395e+08              14.70   
4                                       28.1  1.366418e+09               5.36   
..                                       ...           ...                ...   
990                                     51.3  2.125594e+08              12.08   
991                                     28.1  1.366418e+09               5.36   
992                                     60.0  6.683440e+07               3.85   

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам



In [ ]:
df.columns

Index(['rank', 'Youtuber', 'subscribers', 'video views', 'category', 'Title',
       'uploads', 'Country', 'Abbreviation', 'channel_type',
       'video_views_rank', 'country_rank', 'channel_type_rank',
       'video_views_for_the_last_30_days', 'lowest_monthly_earnings',
       'highest_monthly_earnings', 'lowest_yearly_earnings',
       'highest_yearly_earnings', 'subscribers_for_last_30_days',
       'created_year', 'created_month', 'created_date',
       'Gross tertiary education enrollment (%)', 'Population',
       'Unemployment rate', 'Urban_population', 'Latitude', 'Longitude'],
      dtype='object')

In [6]:
print(df.head(5))

   rank                    Youtuber  subscribers   video views  \
0     1                    T-Series    245000000  2.280000e+11   
1     2              YouTube Movies    170000000  0.000000e+00   
2     3                     MrBeast    166000000  2.836884e+10   
3     4  Cocomelon - Nursery Rhymes    162000000  1.640000e+11   
4     5                   SET India    159000000  1.480000e+11   

           category                       Title  uploads        Country  \
0             Music                    T-Series    20082          India   
1  Film & Animation               youtubemovies        1  United States   
2     Entertainment                     MrBeast      741  United States   
3         Education  Cocomelon - Nursery Rhymes      966  United States   
4             Shows                   SET India   116536          India   

  Abbreviation   channel_type  ...  subscribers_for_last_30_days  \
0           IN          Music  ...                     2000000.0   
1           US  

In [7]:
print(df.tail(5))

     rank                  Youtuber  subscribers   video views  \
990   991             Natan por Aï¿     12300000  9.029610e+09   
991   992  Free Fire India Official     12300000  1.674410e+09   
992   993                     Panda     12300000  2.214684e+09   
993   994               RobTopGames     12300000  3.741235e+08   
994   995              Make Joke Of     12300000  2.129774e+09   

           category                     Title  uploads         Country  \
990          Sports             Natan por Aï¿     1200          Brazil   
991  People & Blogs  Free Fire India Official     1500           India   
992             NaN               HybridPanda     2452  United Kingdom   
993          Gaming               RobTopGames       39          Sweden   
994          Comedy              Make Joke Of       62           India   

    Abbreviation   channel_type  ...  subscribers_for_last_30_days  \
990           BR  Entertainment  ...                      700000.0   
991           IN  

In [8]:

print(df.describe(include="all"))


             rank  Youtuber   subscribers   video views       category  \
count   995.00000       995  9.950000e+02  9.950000e+02            949   
unique        NaN       995           NaN           NaN             18   
top           NaN  T-Series           NaN           NaN  Entertainment   
freq          NaN         1           NaN           NaN            241   
mean    498.00000       NaN  2.298241e+07  1.103954e+10            NaN   
std     287.37606       NaN  1.752611e+07  1.411084e+10            NaN   
min       1.00000       NaN  1.230000e+07  0.000000e+00            NaN   
25%     249.50000       NaN  1.450000e+07  4.288145e+09            NaN   
50%     498.00000       NaN  1.770000e+07  7.760820e+09            NaN   
75%     746.50000       NaN  2.460000e+07  1.355470e+10            NaN   
max     995.00000       NaN  2.450000e+08  2.280000e+11            NaN   

          Title        uploads        Country Abbreviation   channel_type  \
count       995     995.000000    

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета



*Курсив*

1.   subscribers - 22982412.060302, video views - 1.103954e+10, uploads - 9187.125628, subscribers_for_last_30_days - 3.490791e+05, created_year - 2012.630303 created_date - 15.746465, Gross tertiary education enrollment (%) - 63.627752 Population - 4.303873e+08, Unemployment rate - 9.279278, Urban_population - 2.242150e+08, Latitude - 26.632783 Longitude - -14.128146
2. subscribers - min: 12300000.0 max:245000000.0 , video views - min:0.000000e+00 max:2.280000e+11 , uploads min:0.000000 max:301308.000000 , subscribers_for_last_30_days min:1.000000e+00 max:8.000000e+06 , created_year min:1970.000000 max:2022.000000 created_date min:1.000000 max: 31.000000 , Gross tertiary education enrollment (%) - min:7.600000 max:113.100000, Population min:2.025060e+05 max:1.397715e+09 , Unemployment rate min:0.750000 max:14.720000 , Urban_population min:3.558800e+04 max: 8.429340e+08 , Latitude min:-38.416097 max:61.924110 Longitude - min:-172.104629 max:138.252924




##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [9]:

"""
df = df.astype({"a": "Int64"})

df = df.astype({"a": "float64"})

"""
df.Youtuber = df.Youtuber.astype("category")
df.category = df.category.astype("category")
df.Title = df.Title.astype("category")
df.Country = df.Country.astype("category")
df.Abbreviation = df.Abbreviation.astype("category")
df.channel_type = df.channel_type.astype("category")
df.created_month = df.created_month.astype("category")
print(df.dtypes)

rank                                          int64
Youtuber                                   category
subscribers                                   int64
video views                                 float64
category                                   category
Title                                      category
uploads                                       int64
Country                                    category
Abbreviation                               category
channel_type                               category
video_views_rank                            float64
country_rank                                float64
channel_type_rank                           float64
video_views_for_the_last_30_days            float64
lowest_monthly_earnings                     float64
highest_monthly_earnings                    float64
lowest_yearly_earnings                      float64
highest_yearly_earnings                     float64
subscribers_for_last_30_days                float64
created_year

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?

Ответ:
subscribers - числовые-количественные rank - числовые-порядковые category - категориальные

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [10]:
df[df["rank"] < 10]

rank                    Youtuber  subscribers   video views  \
0     1                    T-Series    245000000  2.280000e+11   
1     2              YouTube Movies    170000000  0.000000e+00   
2     3                     MrBeast    166000000  2.836884e+10   
3     4  Cocomelon - Nursery Rhymes    162000000  1.640000e+11   
4     5                   SET India    159000000  1.480000e+11   
5     6                       Music    119000000  0.000000e+00   
6     7         ýýý Kids Diana Show    112000000  9.324704e+10   
7     8                   PewDiePie    111000000  2.905804e+10   
8     9                 Like Nastya    106000000  9.047906e+10   

           category                       Title  uploads        Country  \
0             Music                    T-Series    20082          India   
1  Film & Animation               youtubemovies        1  United States   
2     Entertainment                     MrBeast      741  United States   
3         Education  Cocomelon - Nursery Rhymes      966  United States   
4             Shows                   SET India   116536          India   
5               NaN                       Music        0            NaN   
6    People & Blogs         ýýý Kids Diana Show     1111  United States   
7            Gaming                   PewDiePie     4716          Japan   
8    People & Blogs            Like Nastya Vlog      493         Russia   

  Abbreviation   channel_type  ...  subscribers_for_last_30_days  \
0           IN          Music  ...                     2000000.0   
1           US          Games  ...                           NaN   
2           US  Entertainment  ...                     8000000.0   
3           US      Education  ...                     1000000.0   
4           IN  Entertainment  ...                     1000000.0   
5          NaN          Music  ...                           NaN   
6           US  Entertainment  ...                           NaN   
7           JP  Entertainment  ...                           NaN   
8           RU         People  ...                      100000.0   

   created_year  created_month  created_date  \
0        2006.0            Mar          13.0   
1        2006.0            Mar           5.0   
2        2012.0            Feb          20.0   
3        2006.0            Sep           1.0   
4        2006.0            Sep          20.0   
5        2013.0            Sep          24.0   
6        2015.0            May          12.0   
7        2010.0            Apr          29.0   
8        2016.0            Jan          14.0   

   Gross tertiary education enrollment (%)    Population  Unemployment rate  \
0                                     28.1  1.366418e+09               5.36   
1                                     88.2  3.282395e+08              14.70   
2                                     88.2  3.282395e+08              14.70   
3                                     88.2  3.282395e+08              14.70   
4                                     28.1  1.366418e+09               5.36   
5                                      NaN           NaN                NaN   
6                                     88.2  3.282395e+08              14.70   
7                                     63.2  1.262266e+08               2.29   
8                                     81.9  1.443735e+08               4.59   

   Urban_population   Latitude   Longitude  
0       471031528.0  20.593684   78.962880  
1       270663028.0  37.090240  -95.712891  
2       270663028.0  37.090240  -95.712891  
3       270663028.0  37.090240  -95.712891  
4       471031528.0  20.593684   78.962880  
5               NaN        NaN         NaN  
6       270663028.0  37.090240  -95.712891  
7       115782416.0  36.204824  138.252924  
8       107683889.0  61.524010  105.318756  

[9 rows x 28 columns]

In [11]:

df[df["subscribers"] < 100000000]

rank                  Youtuber  subscribers   video views  \
9      10             Vlad and Niki     98900000  7.718017e+10   
10     11         Zee Music Company     96700000  5.785629e+10   
11     12                       WWE     96000000  7.742847e+10   
12     13                    Gaming     93600000  0.000000e+00   
13     14                 BLACKPINK     89800000  3.214460e+10   
..    ...                       ...          ...           ...   
990   991             Natan por Aï¿     12300000  9.029610e+09   
991   992  Free Fire India Official     12300000  1.674410e+09   
992   993                     Panda     12300000  2.214684e+09   
993   994               RobTopGames     12300000  3.741235e+08   
994   995              Make Joke Of     12300000  2.129774e+09   

           category                     Title  uploads         Country  \
9     Entertainment             Vlad and Niki      574   United States   
10            Music         Zee Music Company     8548           India   
11           Sports                       WWE    70127   United States   
12              NaN                    Gaming        0             NaN   
13   People & Blogs                 BLACKPINK      543     South Korea   
..              ...                       ...      ...             ...   
990          Sports             Natan por Aï¿     1200          Brazil   
991  People & Blogs  Free Fire India Official     1500           India   
992             NaN               HybridPanda     2452  United Kingdom   
993          Gaming               RobTopGames       39          Sweden   
994          Comedy              Make Joke Of       62           India   

    Abbreviation   channel_type  ...  subscribers_for_last_30_days  \
9             US  Entertainment  ...                      600000.0   
10            IN          Music  ...                     1100000.0   
11            US         Sports  ...                      600000.0   
12           NaN          Games  ...                           NaN   
13            KR          Music  ...                      700000.0   
..           ...            ...  ...                           ...   
990           BR  Entertainment  ...                      700000.0   
991           IN          Games  ...                      300000.0   
992           GB          Games  ...                        1000.0   
993           SE          Games  ...                      100000.0   
994           IN         Comedy  ...                      100000.0   

     created_year  created_month  created_date  \
9          2018.0            Apr          23.0   
10         2014.0            Mar          12.0   
11         2007.0            May          11.0   
12         2013.0            Dec          15.0   
13         2016.0            Jun          29.0   
..            ...            ...           ...   
990        2017.0            Feb          12.0   
991        2018.0            Sep          14.0   
992        2006.0            Sep          11.0   
993        2012.0            May           9.0   
994        2017.0            Aug           1.0   

     Gross tertiary education enrollment (%)    Population  Unemployment rate  \
9                                       88.2  3.282395e+08              14.70   
10                                      28.1  1.366418e+09               5.36   
11                                      88.2  3.282395e+08              14.70   
12                                       NaN           NaN                NaN   
13                                      94.3  5.170910e+07               4.15   
..                                       ...           ...                ...   
990                                     51.3  2.125594e+08              12.08   
991                                     28.1  1.366418e+09               5.36   
992                                     60.0  6.683440e+07               3.85   
993                                     67.0  1.028545e+07             

In [12]:
df[df["uploads"] < 10]

rank               Youtuber  subscribers   video views          category  \
1       2         YouTube Movies    170000000  0.000000e+00  Film & Animation   
5       6                  Music    119000000  0.000000e+00               NaN   
12     13                 Gaming     93600000  0.000000e+00               NaN   
14     15              Goldmines     86900000  2.411823e+10  Film & Animation   
16     17        5-Minute Crafts     80100000  2.623679e+10     Howto & Style   
..    ...                    ...          ...           ...               ...   
967   968  Troom Troom Indonesia     12500000  5.379684e+09    People & Blogs   
975   976      Gustavo Parï¿½ï¿½     12400000  2.602614e+09            Comedy   
983   984               MoniLina     12400000  1.608681e+10            Comedy   
985   986                   TKOR     12400000  3.392023e+09         Education   
986   987              ANNA KOVA     12400000  1.395959e+10    People & Blogs   

                     Title  uploads         Country Abbreviation  \
1            youtubemovies        1   United States           US   
5                    Music        0             NaN          NaN   
12                  Gaming        0             NaN          NaN   
14               goldmines        1             NaN          NaN   
16     5-Minute Crafts 2.0        1  United Kingdom           GB   
..                     ...      ...             ...          ...   
967  TROOM TROOM INDONESIA        8             NaN          NaN   
975        GustavoParodias        9          Brazil           BR   
983         MoniLinaFamily        0   United States           US   
985                   TKoR        0             NaN          NaN   
986               annakova        1             NaN          NaN   

      channel_type  ...  subscribers_for_last_30_days  created_year  \
1            Games  ...                           NaN        2006.0   
5            Music  ...                           NaN        2013.0   
12           Games  ...                           NaN        2013.0   
14           Music  ...                           NaN        2006.0   
16   Entertainment  ...                           NaN        2020.0   
..             ...  ...                           ...           ...   
967         People  ...                           NaN        2020.0   
975         Comedy  ...                           NaN        2010.0   
983         People  ...                         100.0        2016.0   
985         People  ...                           NaN        2006.0   
986           Film  ...                           NaN        2006.0   

     created_month  created_date  Gross tertiary education enrollment (%)  \
1              Mar           5.0                                     88.2   
5              Sep          24.0                                      NaN   
12             Dec          15.0                                      NaN   
14             Aug          15.0                                      NaN   
16             Jul          27.0                                     60.0   
..             ...           ...                                      ...   
967            Jul          29.0                                      NaN   
975            Aug          24.0                                     51.3   
983            May          10.0                                     88.2   
985            Aug          16.0                                      NaN   
986            Jun          18.0                                      NaN   

      Population  Unemployment rate  Urban_population   Latitude  Longitude  
1    328239523.0              14.70       270663028.0  37.090240 -95.712891  
5            NaN                NaN               NaN        NaN        NaN  
12           NaN                NaN               NaN        NaN        NaN  
14           NaN                NaN               NaN        NaN        NaN  
16    66834405.0               3.85        5590

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [13]:

df.groupby(["subscribers"]).count()

rank  Youtuber  video views  category  Title  uploads  Country  \
subscribers                                                                   
12300000        5         5            5         4      5        5        5   
12400000       20        20           20        19     20       20       17   
12500000       22        22           22        20     22       22       19   
12600000        5         5            5         5      5        5        5   
12700000       13        13           13        10     13       13       10   
...           ...       ...          ...       ...    ...      ...      ...   
159000000       1         1            1         1      1        1        1   
162000000       1         1            1         1      1        1        1   
166000000       1         1            1         1      1        1        1   
170000000       1         1            1         1      1        1        1   
245000000       1         1            1         1      1        1        1   

             Abbreviation  channel_type  video_views_rank  ...  \
subscribers                                                ...   
12300000                5             5                 5  ...   
12400000               17            20                20  ...   
12500000               19            20                22  ...   
12600000                5             5                 5  ...   
12700000               10            13                13  ...   
...                   ...           ...               ...  ...   
159000000               1             1                 1  ...   
162000000               1             1                 1  ...   
166000000               1             1                 1  ...   
170000000               1             1                 1  ...   
245000000               1             1                 1  ...   

             subscribers_for_last_30_days  created_year  created_month  \
subscribers                                                              
12300000                                5             5              5   
12400000                                9            20             20   
12500000                                9            22             22   
12600000                                3             5              5   
12700000                                8            13             13   
...                                   ...           ...            ...   
159000000                               1             1              1   
162000000                               1             1              1   
166000000                               1             1              1   
170000000                               0             1              1   
245000000                               1             1              1   

             created_date  Gross tertiary education enrollment (%)  \
subscribers                                                          
12300000                5                                        5   
12400000               20                                       17   
12500000               22                                       19   
12600000                5                                        5   
12700000               13                                       10   
...                   ...                                      ...   
159000000               1                                        1   
162000000               1                                        1   
166000000               1                                        1   
170000000               1                                        1   
245000000               1                                        1   

             Population  Unemployment rate  Urban_population  Latitude  \
subscribers                                                              
12300000              5                  5                 5         5   
12400000             17       

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация